import { useState, useEffect } from 'react'
import axios from 'axios'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

export default function PatientDetails({ patientId, onClose }) {
  const [patient, setPatient] = useState(null)
  const [testHistory, setTestHistory] = useState([])
  const [appointments, setAppointments] = useState([])
  const [loading, setLoading] = useState(true)
  const [activeTab, setActiveTab] = useState('overview')

  useEffect(() => {
    if (patientId) {
      fetchPatientDetails()
    }
  }, [patientId])

  const fetchPatientDetails = async () => {
    try {
      setLoading(true)
      const token = localStorage.getItem('token')
      
      // Fetch patient info
      const patientRes = await axios.get(`${API_URL}/api/patients/${patientId}`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      setPatient(patientRes.data)
      
      // Fetch test history
      const historyRes = await axios.get(`${API_URL}/api/patients/${patientId}/history`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      setTestHistory(historyRes.data || [])
      
      // Fetch appointments
      const appointmentsRes = await axios.get(`${API_URL}/api/appointments`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      setAppointments(appointmentsRes.data.filter(a => a.patient_id === patientId) || [])
    } catch (error) {
      console.error('Error fetching patient details:', error)
    } finally {
      setLoading(false)
    }
  }

  const generateReport = () => {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Patient Report - ${patient?.name}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; }
          .header { text-align: center; border-bottom: 3px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
          .section { margin: 20px 0; }
          .label { font-weight: bold; color: #4b5563; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
          th { background-color: #f3f4f6; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Patient Medical Report</h1>
          <p>Generated on ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="section">
          <h2>Patient Information</h2>
          <p><span class="label">Name:</span> ${patient?.name || 'N/A'}</p>
          <p><span class="label">Patient ID:</span> ${patient?.patient_id || 'N/A'}</p>
          <p><span class="label">Age:</span> ${patient?.age || 'N/A'}</p>
          <p><span class="label">Gender:</span> ${patient?.gender || 'N/A'}</p>
        </div>
        
        <div class="section">
          <h2>Test History (${testHistory.length} tests)</h2>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Result</th>
                <th>Confidence</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              ${testHistory.map(test => `
                <tr>
                  <td>${new Date(test.created_at).toLocaleDateString()}</td>
                  <td>${test.prediction}</td>
                  <td>${(test.confidence * 100).toFixed(1)}%</td>
                  <td>${test.doctor_notes || 'No notes'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="section">
          <h2>Appointments (${appointments.length})</h2>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Status</th>
                <th>Reason</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              ${appointments.map(apt => `
                <tr>
                  <td>${new Date(apt.appointment_date).toLocaleString()}</td>
                  <td>${apt.status}</td>
                  <td>${apt.reason}</td>
                  <td>${apt.notes || 'No notes'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="section">
          <p style="text-align: center; color: #6b7280; font-size: 12px; margin-top: 40px;">
            This report is generated by ParaDetect AI - Confidential Medical Information
          </p>
        </div>
      </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      </div>
    )
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-white rounded-lg max-w-6xl w-full my-8">
        {/* Header */}
        <div className="px-6 py-4 border-b flex justify-between items-center bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-t-lg">
          <div>
            <h2 className="text-2xl font-bold">Patient Details</h2>
            <p className="text-sm opacity-90">{patient?.name} - {patient?.patient_id}</p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={generateReport}
              className="px-4 py-2 bg-white text-blue-600 rounded-lg hover:bg-gray-100 font-semibold"
            >
              📄 Generate Report
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 bg-white bg-opacity-20 hover:bg-opacity-30 rounded-lg font-semibold"
            >
              ✕ Close
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="border-b">
          <div className="flex px-6">
            {['overview', 'test-history', 'appointments'].map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`py-4 px-6 border-b-2 font-medium capitalize transition-colors ${
                  activeTab === tab
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700'
                }`}
              >
                {tab.replace('-', ' ')}
              </button>
            ))}
          </div>
        </div>

        {/* Content */}
        <div className="p-6 max-h-[600px] overflow-y-auto">
          {/* Overview Tab */}
          {activeTab === 'overview' && (
            <div className="space-y-6">
              {/* Patient Info Card */}
              <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Patient Information</h3>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-sm text-gray-600">Full Name</p>
                    <p className="font-semibold text-gray-900">{patient?.name || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Patient ID</p>
                    <p className="font-semibold text-gray-900">{patient?.patient_id || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Age</p>
                    <p className="font-semibold text-gray-900">{patient?.age || 'N/A'} years</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Gender</p>
                    <p className="font-semibold text-gray-900">{patient?.gender || 'N/A'}</p>
                  </div>
                </div>
              </div>

              {/* Statistics */}
              <div className="grid grid-cols-3 gap-4">
                <div className="bg-white border-2 border-blue-200 rounded-lg p-4 text-center">
                  <p className="text-3xl font-bold text-blue-600">{testHistory.length}</p>
                  <p className="text-sm text-gray-600 mt-1">Total Tests</p>
                </div>
                <div className="bg-white border-2 border-green-200 rounded-lg p-4 text-center">
                  <p className="text-3xl font-bold text-green-600">
                    {testHistory.filter(t => t.prediction === 'Uninfected').length}
                  </p>
                  <p className="text-sm text-gray-600 mt-1">Negative Results</p>
                </div>
                <div className="bg-white border-2 border-red-200 rounded-lg p-4 text-center">
                  <p className="text-3xl font-bold text-red-600">
                    {testHistory.filter(t => t.prediction === 'Parasitized').length}
                  </p>
                  <p className="text-sm text-gray-600 mt-1">Positive Results</p>
                </div>
              </div>

              {/* Recent Activity */}
              <div className="bg-white border rounded-lg p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Recent Activity</h3>
                <div className="space-y-3">
                  {testHistory.slice(0, 3).map((test, index) => (
                    <div key={index} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
                      <div className={`w-3 h-3 rounded-full ${
                        test.prediction === 'Parasitized' ? 'bg-red-500' : 'bg-green-500'
                      }`}></div>
                      <div className="flex-1">
                        <p className="text-sm font-semibold text-gray-900">
                          Test Result: {test.prediction}
                        </p>
                        <p className="text-xs text-gray-600">
                          {new Date(test.created_at).toLocaleString()}
                        </p>
                      </div>
                      <span className="text-sm font-semibold text-gray-700">
                        {(test.confidence * 100).toFixed(1)}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Test History Tab */}
          {activeTab === 'test-history' && (
            <div className="space-y-4">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-bold text-gray-900">
                  Test History ({testHistory.length} tests)
                </h3>
              </div>

              {testHistory.length === 0 ? (
                <div className="text-center py-12">
                  <span className="text-6xl">🔬</span>
                  <p className="mt-4 text-lg text-gray-600">No test history</p>
                </div>
              ) : (
                testHistory.map((test) => (
                  <div key={test.id} className="bg-white border rounded-lg p-6 hover:shadow-md transition-shadow">
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <span className={`text-xl font-bold ${
                          test.prediction === 'Parasitized' ? 'text-red-600' : 'text-green-600'
                        }`}>
                          {test.prediction}
                        </span>
                        <p className="text-sm text-gray-600 mt-1">
                          {new Date(test.created_at).toLocaleString()}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-sm text-gray-600">Confidence</p>
                        <p className="text-2xl font-bold text-gray-900">
                          {(test.confidence * 100).toFixed(1)}%
                        </p>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4 mb-4">
                      <div className="bg-red-50 rounded-lg p-3">
                        <p className="text-xs text-gray-600">Parasitized</p>
                        <p className="text-lg font-bold text-red-600">
                          {(test.prob_parasitized * 100).toFixed(1)}%
                        </p>
                      </div>
                      <div className="bg-green-50 rounded-lg p-3">
                        <p className="text-xs text-gray-600">Uninfected</p>
                        <p className="text-lg font-bold text-green-600">
                          {(test.prob_uninfected * 100).toFixed(1)}%
                        </p>
                      </div>
                    </div>

                    {test.doctor_notes && (
                      <div className="bg-blue-50 rounded-lg p-4">
                        <p className="text-sm font-semibold text-blue-900 mb-1">Doctor's Notes:</p>
                        <p className="text-sm text-blue-800">{test.doctor_notes}</p>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          )}

          {/* Appointments Tab */}
          {activeTab === 'appointments' && (
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-gray-900 mb-4">
                Appointments ({appointments.length})
              </h3>

              {appointments.length === 0 ? (
                <div className="text-center py-12">
                  <span className="text-6xl">📅</span>
                  <p className="mt-4 text-lg text-gray-600">No appointments</p>
                </div>
              ) : (
                appointments.map((apt) => (
                  <div key={apt.id} className="bg-white border rounded-lg p-6">
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <p className="text-lg font-bold text-gray-900">
                          {new Date(apt.appointment_date).toLocaleDateString()}
                        </p>
                        <p className="text-sm text-gray-600">
                          {new Date(apt.appointment_date).toLocaleTimeString()}
                        </p>
                      </div>
                      <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
                        apt.status === 'scheduled' ? 'bg-blue-100 text-blue-800' :
                        apt.status === 'completed' ? 'bg-green-100 text-green-800' :
                        'bg-gray-100 text-gray-800'
                      }`}>
                        {apt.status}
                      </span>
                    </div>

                    <div className="mb-4">
                      <p className="text-sm font-semibold text-gray-700">Reason:</p>
                      <p className="text-sm text-gray-600">{apt.reason}</p>
                    </div>

                    {apt.notes && (
                      <div className="bg-blue-50 rounded-lg p-4">
                        <p className="text-sm font-semibold text-blue-900 mb-1">Notes:</p>
                        <p className="text-sm text-blue-800">{apt.notes}</p>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
